### ISSUE TITLE
Throws error if /middleware doesn't exist

### ISSUE THREAD

**Issue by toniengelhardt** [loonpwn/nuxt-build-optimisations#7]
**Describe the bug**

Throws a friendly error if the middleware directory doesn't exist.

```
ERROR  Failed to compile with 1 errors                                       

This relative module was not found:                                           
                                                                             
* ./middleware in ./.nuxt/auth.js    
```

**To Reproduce**

- Open a Nuxt project without middleware folder
- Start dev server

**Expected behavior**

Should work also without middleware dir, if you don't have any middleware there is no need for the directory. Nuxt itself also allows it.

**Screenshots**

<img width="336" alt="Screen Shot 2021-02-11 at 19 32 43" src="https://user-images.githubusercontent.com/2703233/107688763-ec00b000-6c9f-11eb-8643-aa2d2f56db20.png">

**Comment by loonpwn** [comment]
Thank you @toniengelhardt 

Previously I was disabling the middleware nuxt feature if you didn't have the folder, but that was clearly a mistake.

The next patch won't have this logic and will resolve your issue.

**Comment by toniengelhardt** [comment]
Great module btw!
